// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWEdx3yIe9ngmW7WLpq9rBM_GI__qRKwQ',
    appId: '1:979386213767:web:2885ec7852f63b8cc0df22',
    messagingSenderId: '979386213767',
    projectId: 'whatsapp-messenger-a5dec',
    authDomain: 'whatsapp-messenger-a5dec.firebaseapp.com',
    storageBucket: 'whatsapp-messenger-a5dec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMiGtx218OwJuK_OeItZ4uvPZAJzX36sA',
    appId: '1:979386213767:android:838404a4f8c743c0c0df22',
    messagingSenderId: '979386213767',
    projectId: 'whatsapp-messenger-a5dec',
    storageBucket: 'whatsapp-messenger-a5dec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSBRZ2g1vkr3k93AU2WiEGIcDumAFdqw',
    appId: '1:979386213767:ios:9ba4c476df7ec8d5c0df22',
    messagingSenderId: '979386213767',
    projectId: 'whatsapp-messenger-a5dec',
    storageBucket: 'whatsapp-messenger-a5dec.appspot.com',
    iosClientId: '979386213767-84iekertid215fshudip6j6nn0v5nn1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoSBRZ2g1vkr3k93AU2WiEGIcDumAFdqw',
    appId: '1:979386213767:ios:9ba4c476df7ec8d5c0df22',
    messagingSenderId: '979386213767',
    projectId: 'whatsapp-messenger-a5dec',
    storageBucket: 'whatsapp-messenger-a5dec.appspot.com',
    iosClientId: '979386213767-84iekertid215fshudip6j6nn0v5nn1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSocial',
  );
}
